###  linear Regression

In [1]:
import pandas as pd

In [2]:
x=[]
k=0
for i in range(0,50):
    k=k+1
    x.append(k)
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [3]:
import random 

In [4]:
import numpy as np

In [5]:
x=[]
y=[]
for i in range(1,51):
    x.append(i)
    k=random.random()
    y.append(4*i+5+k)
print(x)
print(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[9.913609615346784, 13.340931924919111, 17.119886459131493, 21.933479916651194, 25.82529114909986, 29.198627424999025, 33.4465652154822, 37.951746861252445, 41.06925042910247, 45.033625171012616, 49.55950367359874, 53.93205743552363, 57.44461360473566, 61.69935934326399, 65.55124104315612, 69.25805954706728, 73.38344196734862, 77.45875112897674, 81.88717335902066, 85.20363546755142, 89.58738456746477, 93.80335132723572, 97.35989110443745, 101.97730519454542, 105.15591622686425, 109.14307248250317, 113.99409942984767, 117.8886690052712, 121.17289160737202, 125.90898705126364, 129.8115798484309, 133.4124953402015, 137.11916408463577, 141.37578586677205, 145.40002622210008, 149.3662286930257, 153.8443220010457, 157.40862493589574, 161.64862644800223, 165.12315378734547, 169.2676941796838, 173.1719826

In [6]:
x1=[]
y1=[]
x2=[]
y2=[]
for i in range(0,35):
    x1.append(x[i])
    y1.append(y[i])
for i in range(0,15):
    x2.append(x[i+35])
    y2.append(y[i+35])
print(x1)
print(y1)
print(x2)
print(y2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
[9.913609615346784, 13.340931924919111, 17.119886459131493, 21.933479916651194, 25.82529114909986, 29.198627424999025, 33.4465652154822, 37.951746861252445, 41.06925042910247, 45.033625171012616, 49.55950367359874, 53.93205743552363, 57.44461360473566, 61.69935934326399, 65.55124104315612, 69.25805954706728, 73.38344196734862, 77.45875112897674, 81.88717335902066, 85.20363546755142, 89.58738456746477, 93.80335132723572, 97.35989110443745, 101.97730519454542, 105.15591622686425, 109.14307248250317, 113.99409942984767, 117.8886690052712, 121.17289160737202, 125.90898705126364, 129.8115798484309, 133.4124953402015, 137.11916408463577, 141.37578586677205, 145.40002622210008]
[36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[149.3662286930257, 153.8443220010457, 157.40862493589574, 161.64862644800223, 165.12315378734547, 169.2676941796838, 173.17198

In [7]:
x1=np.array(x1)
x2=np.array(x2)
y1=np.array(y1)
y2=np.array(y2)
print(x1)
print(y1)
print(x2)
print(y2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]
[  9.91360962  13.34093192  17.11988646  21.93347992  25.82529115
  29.19862742  33.44656522  37.95174686  41.06925043  45.03362517
  49.55950367  53.93205744  57.4446136   61.69935934  65.55124104
  69.25805955  73.38344197  77.45875113  81.88717336  85.20363547
  89.58738457  93.80335133  97.3598911  101.97730519 105.15591623
 109.14307248 113.99409943 117.88866901 121.17289161 125.90898705
 129.81157985 133.41249534 137.11916408 141.37578587 145.40002622]
[36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[149.36622869 153.844322   157.40862494 161.64862645 165.12315379
 169.26769418 173.17198261 177.75962836 181.55016842 185.79496987
 189.63916108 193.06881493 197.89378317 201.74013704 205.50566871]


In [8]:
w0=random.random()
w1=random.random()
yp1=w0+w1*x1
print(yp1)
print(y1)

[ 1.15624433  1.49251653  1.82878873  2.16506093  2.50133313  2.83760533
  3.17387753  3.51014973  3.84642193  4.18269414  4.51896634  4.85523854
  5.19151074  5.52778294  5.86405514  6.20032734  6.53659954  6.87287175
  7.20914395  7.54541615  7.88168835  8.21796055  8.55423275  8.89050495
  9.22677715  9.56304936  9.89932156 10.23559376 10.57186596 10.90813816
 11.24441036 11.58068256 11.91695476 12.25322697 12.58949917]
[  9.91360962  13.34093192  17.11988646  21.93347992  25.82529115
  29.19862742  33.44656522  37.95174686  41.06925043  45.03362517
  49.55950367  53.93205744  57.4446136   61.69935934  65.55124104
  69.25805955  73.38344197  77.45875113  81.88717336  85.20363547
  89.58738457  93.80335133  97.3598911  101.97730519 105.15591623
 109.14307248 113.99409943 117.88866901 121.17289161 125.90898705
 129.81157985 133.41249534 137.11916408 141.37578587 145.40002622]


In [9]:
error=(sum((y1-yp1)**2))/70
error

3179.9899499080766

In [10]:
dj0=(sum((y1-yp1)))/35

In [11]:
dj0

70.65059882814535

In [12]:
dj1=(sum((y1-yp1)*x1))/35

In [13]:
dj1

1645.3072506444646

In [14]:
alpha=0.001

In [15]:
w0=w0+alpha*dj0

In [16]:
w1=w1+alpha*dj1

In [17]:
w0

0.8906227226994919

In [18]:
w1

1.9815794518755774

In [19]:
yp1=w0+w1*x1

In [20]:
yp1

array([ 2.87220217,  4.85378163,  6.83536108,  8.81694053, 10.79851998,
       12.78009943, 14.76167889, 16.74325834, 18.72483779, 20.70641724,
       22.68799669, 24.66957615, 26.6511556 , 28.63273505, 30.6143145 ,
       32.59589395, 34.5774734 , 36.55905286, 38.54063231, 40.52221176,
       42.50379121, 44.48537066, 46.46695012, 48.44852957, 50.43010902,
       52.41168847, 54.39326792, 56.37484738, 58.35642683, 60.33800628,
       62.31958573, 64.30116518, 66.28274463, 68.26432409, 70.24590354])

In [21]:
y1

array([  9.91360962,  13.34093192,  17.11988646,  21.93347992,
        25.82529115,  29.19862742,  33.44656522,  37.95174686,
        41.06925043,  45.03362517,  49.55950367,  53.93205744,
        57.4446136 ,  61.69935934,  65.55124104,  69.25805955,
        73.38344197,  77.45875113,  81.88717336,  85.20363547,
        89.58738457,  93.80335133,  97.3598911 , 101.97730519,
       105.15591623, 109.14307248, 113.99409943, 117.88866901,
       121.17289161, 125.90898705, 129.81157985, 133.41249534,
       137.11916408, 141.37578587, 145.40002622])

In [22]:
error=(sum((y1-yp1)**2))/70
error

1046.6560016308204

In [23]:
while(error>1):
    dj0=(sum((y1-yp1)))/35
    dj1=(sum((y1-yp1)*x1))/35
    w0=w0+alpha*dj0
    w1=w1+alpha*dj1
    yp1=w0+w1*x1
    error=(sum((y1-yp1)**2))/70
    print(error)

345.63534900652604
115.27708851089639
39.579884645165535
14.70476250569482
6.529927347349661
3.842856341180674
2.9590812716991155
2.667874968988728
2.5713888984195297
2.538888852824249
2.5274151842855375
2.522851225061281
2.520558196133631
2.5190117807950507
2.51771108387888
2.5164915095684535
2.5152989710098184
2.5141156949215584
2.5129358407698814
2.5117574891572936
2.5105800091833657
2.5094031933517433
2.5082269732979747
2.5070513263768484
2.505876244966698
2.5047017263827667
2.503527769562638
2.5023543739770995
2.501181539272217
2.500009265151767
2.4988375513385654
2.4976663975617597
2.496495803552678
2.49532576904344
2.494156293766524
2.4929873774545896
2.4918190198404804
2.4906512206571376
2.4894839796376678
2.4883172965152847
2.4871511710233243
2.485985602895272
2.4848205918647177
2.4836561376654047
2.482492240031171
2.481328898696019
2.4801661133940365
2.479003883859487
2.477842209826707
2.4766810910302115
2.4755205272046084
2.4743605180846315
2.4732010634051775
2.4720421629012

1.6443364858843534
1.6435737513158122
1.642811381305569
1.6420493756793701
1.641287734263053
1.6405264568825417
1.639765543363842
1.6390049935330389
1.6382448072163054
1.637484984239898
1.6367255244301426
1.6359664276134758
1.6352076936163873
1.6344493222654648
1.6336913133873914
1.6329336668088987
1.6321763823568305
1.631419459858108
1.6306628991397196
1.6299067000287615
1.629150862352388
1.628395385937856
1.62764027061249
1.6268855162037057
1.6261311225390027
1.6253770894459436
1.6246234167522022
1.623870104285521
1.6231171518737222
1.622364559344707
1.6216123265264761
1.620860453247095
1.6201089393347219
1.6193577846175937
1.6186069889240173
1.6178565520824035
1.617106473921234
1.616356754269073
1.6156073929545596
1.6148583898064302
1.6141097446534887
1.6133614573246373
1.6126135276488363
1.6118659554551475
1.611118740572707
1.6103718828307414
1.6096253820585347
1.6088792380854797
1.6081334507410372
1.6073880198547594
1.6066429452562652
1.6058982267752582
1.6051538642415395
1.604409

1.0266034119543714
1.0261359304437043
1.0256686723715236
1.0252016376310435
1.02473482611551
1.0242682377182355
1.0238018723325795
1.0233357298519472
1.022869810169798
1.022404113179647
1.0219386387750495
1.0214733868496217
1.0210083572970259
1.0205435500109838
1.020078964885247
1.0196146018136403
1.0191504606900301
1.0186865414083277
1.0182228438625087
1.0177593679465868
1.0172961135546321
1.016833080580765
1.0163702689191578
1.0159076784640264
1.0154453091096436
1.0149831607503406
1.0145212332804772
1.0140595265944892
1.0135980405868381
1.0131367751520541
1.0126757301847162
1.0122149055794367
1.011754301230906
1.011293917033836
1.010833752883012
1.0103738086732543
1.0099140842994496
1.0094545796565084
1.008995294639419
1.0085362291432078
1.00807738306295
1.0076187562937706
1.0071603487308523
1.0067021602694224
1.006244190804752
1.0057864402321792
1.0053289084470693
1.0048715953448597
1.0044145008210261
1.0039576247711002
1.003500967090651
1.0030445276753117
1.0025883064207577
1.00213

In [24]:
yp2=w0+w1*x2

In [25]:
yp2

array([150.9765846 , 155.09474375, 159.21290291, 163.33106206,
       167.44922121, 171.56738036, 175.68553952, 179.80369867,
       183.92185782, 188.04001697, 192.15817613, 196.27633528,
       200.39449443, 204.51265358, 208.63081274])

In [26]:
y2

array([149.36622869, 153.844322  , 157.40862494, 161.64862645,
       165.12315379, 169.26769418, 173.17198261, 177.75962836,
       181.55016842, 185.79496987, 189.63916108, 193.06881493,
       197.89378317, 201.74013704, 205.50566871])

In [27]:
z=[yp2,y2]

In [28]:
z

[array([150.9765846 , 155.09474375, 159.21290291, 163.33106206,
        167.44922121, 171.56738036, 175.68553952, 179.80369867,
        183.92185782, 188.04001697, 192.15817613, 196.27633528,
        200.39449443, 204.51265358, 208.63081274]),
 array([149.36622869, 153.844322  , 157.40862494, 161.64862645,
        165.12315379, 169.26769418, 173.17198261, 177.75962836,
        181.55016842, 185.79496987, 189.63916108, 193.06881493,
        197.89378317, 201.74013704, 205.50566871])]