In [1]:
import pandas as pd
import random 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('logisticcodedata2.csv')

In [3]:
dataset

input1  input2  output
0   4.5192  2.6487       1
1   2.4443  1.5438       1
2   4.2409  1.8990       1
3   5.8097  2.4711       1
4   6.4423  3.3590       1
5   5.8097  3.2406       1
6   6.3917  3.8128       1
7   6.8725  4.4441       1
8   6.7966  3.6747       1
9   8.1630  4.7401       1
10  7.4038  3.8917       1
11  7.6316  4.6020       1
12  7.7581  5.7265       1
13  6.5688  4.9571       1
14  5.3543  3.9903       1
15  4.4686  3.0236       1
16  2.9757  2.0568       1
17  2.4443  1.2676       1
18  0.9008  1.1690       1
19  2.1154  1.7411       1
20  3.2794  1.3860       1
21  4.1650  1.5636       1
22  4.8482  1.8793       1
23  3.3300  2.7868       1
24  5.1518  3.5563       1
25  6.2652  4.0693       1
26  6.2652  4.3849       1
27  7.2014  1.5438       1
28  7.6569  2.4120       1
29  6.1387  1.7806       1
..     ...     ...     ...
70  7.7581  7.7784       0
71  5.1012  7.6009       0
72  4.2156  6.4960       0
73  3.4818  5.8055       0
74  2.3684  5.0163       0
75  1.7864  4.1876       0
76  0.9008  3.4379       0
77  0.9008  5.7857       0
78  1.9636  6.3382       0
79  1.4069  4.9571       0
80  2.4190  6.8511       0
81  2.8745  6.0817       0
82  4.0132  7.1668       0
83  4.6711  7.2260       0
84  5.1771  8.1533       0
85  6.2146  7.4825       0
86  5.4555  7.0484       0
87  5.9868  8.5084       0
88  4.0891  7.5417       0
89  2.3937  7.2063       0
90  1.3310  6.5355       0
91  1.7358  5.4503       0
92  2.4443  5.8449       0
93  3.1781  4.8979       0
94  4.6711  5.8055       0
95  5.9868  7.3641       0
96  4.6711  6.2592       0
97  7.5810  8.3703       0
98  4.6457  8.5676       0
99  4.6457  8.1676       0

[100 rows x 3 columns]

In [4]:
x1=dataset.iloc[:,0]
x2=dataset.iloc[:,1]
y=dataset.iloc[:,-1]

In [5]:
x1=np.array(x1)
x2=np.array(x2)
y=np.array(y)
print(x1)
print(x2)
print(y)

[4.5192 2.4443 4.2409 5.8097 6.4423 5.8097 6.3917 6.8725 6.7966 8.163
 7.4038 7.6316 7.7581 6.5688 5.3543 4.4686 2.9757 2.4443 0.9008 2.1154
 3.2794 4.165  4.8482 3.33   5.1518 6.2652 6.2652 7.2014 7.6569 6.1387
 4.4939 4.8735 5.5314 6.0121 7.1508 7.7075 8.3148 8.5172 8.7449 7.8593
 6.999  5.5061 4.9241 6.6447 7.6822 8.0364 8.9221 7.8593 6.5941 6.0374
 2.7227 1.9383 1.6852 4.3168 3.4312 5.4808 4.1144 3.2034 4.1144 5.1012
 4.8988 5.9615 5.7591 6.6953 5.7338 6.6194 7.2014 7.2014 8.5931 7.7581
 7.7581 5.1012 4.2156 3.4818 2.3684 1.7864 0.9008 0.9008 1.9636 1.4069
 2.419  2.8745 4.0132 4.6711 5.1771 6.2146 5.4555 5.9868 4.0891 2.3937
 1.331  1.7358 2.4443 3.1781 4.6711 5.9868 4.6711 7.581  4.6457 4.6457]
[2.6487 1.5438 1.899  2.4711 3.359  3.2406 3.8128 4.4441 3.6747 4.7401
 3.8917 4.602  5.7265 4.9571 3.9903 3.0236 2.0568 1.2676 1.169  1.7411
 1.386  1.5636 1.8793 2.7868 3.5563 4.0693 4.3849 1.5438 2.412  1.7806
 1.4057 2.6093 3.0828 3.9311 4.7598 5.3122 5.7068 5.1149 5.4109 3.8128
 3.240

In [6]:
w0=random.random()
w1=random.random()
w2=random.random()
yp=w0+(w1*x1)+(w2*x2)
print(yp)
print(y)

[4.74196606 2.91332472 4.37576749 5.70544068 6.37374313 5.8601439
 6.42579936 6.92498159 6.71153229 7.98367056 7.22528828 7.54446569
 7.8684831  6.7929749  5.65826934 4.77815993 3.42790093 2.85779642
 1.64290621 2.6983372  3.5281829  4.24957121 4.84201384 3.84898254
 5.41422907 6.37942345 6.44287288 6.59654767 7.12376845 5.82135082
 4.47247986 5.00836456 5.61294317 6.15567449 7.20392713 7.74601319
 8.29555199 8.33326399 8.56907151 7.56210046 6.78096899 5.55764906
 5.06340437 6.6256472  7.57174135 8.09586091 8.93632448 7.85164377
 6.86809193 6.34186823 3.7397297  2.94597376 2.61514885 4.94224974
 4.12170662 6.01405168 4.86883236 4.08019083 4.97988897 5.88276767
 5.62292236 6.62421309 6.37628968 7.25583317 6.48758047 7.27243831
 7.79840772 7.65958696 8.89578567 8.16200708 8.28100491 6.18819343
 5.28037719 4.57340588 3.5526832  2.93546    2.09905453 2.5710652
 3.50502336 2.79633229 3.96073585 4.15872728 5.25852756 5.77981372
 6.35801623 7.02644875 6.35143635 7.05632362 5.39266507 4.012557

In [7]:
z=1/(1+np.exp(-yp))
z

array([0.99135392, 0.94850121, 0.98757777, 0.99668323, 0.99829714,
       0.99715727, 0.99838338, 0.99901804, 0.99878468, 0.99965913,
       0.99927259, 0.99947125, 0.99961753, 0.99887963, 0.99652358,
       0.9916587 , 0.96856522, 0.94572029, 0.83793   , 0.93692845,
       0.97147911, 0.98593043, 0.99217064, 0.97914289, 0.99556697,
       0.99830677, 0.9984107 , 0.99863679, 0.99919492, 0.99704516,
       0.98870996, 0.99336253, 0.99636297, 0.99788308, 0.99925689,
       0.99956772, 0.99975044, 0.99975967, 0.99981015, 0.99948049,
       0.99886611, 0.99615699, 0.99371575, 0.99867583, 0.99948547,
       0.99969529, 0.99986849, 0.99961104, 0.99896062, 0.99824209,
       0.97679093, 0.95007285, 0.93183019, 0.99291208, 0.98404197,
       0.99756179, 0.99237624, 0.98337676, 0.99317211, 0.99722069,
       0.99639895, 0.99867394, 0.99830147, 0.99929445, 0.99848009,
       0.99930607, 0.99958978, 0.99952872, 0.99986305, 0.99971479,
       0.99974678, 0.99795068, 0.99493527, 0.98978273, 0.97215

In [8]:
error=sum(y*np.log(z)+(1-y)*np.log(1-z))*(-1)
error

267.13103341353656

In [9]:
dj0=-1*sum(y*(1-z)-(1-y)*z)
dj0

48.68092401105919

In [10]:
dj1=-1*sum((y*(1-z)*x1)-((1-y)*z*x1))
dj1

213.54945673202602

In [11]:
dj2=-1*sum((y*(1-z)*x2)-((1-y)*z*x2))
dj2

306.3038951762984

In [12]:
alpha=0.0001

In [13]:
w0=w0+alpha*dj0
w1=w1+alpha*dj1
w2=w2+alpha*dj2

In [14]:
yp1=w0+w1*x1+w2*x2
yp1

array([4.92447213, 3.01767791, 4.52936688, 5.91006536, 6.61907367,
       6.08833866, 6.6839494 , 7.21273606, 6.9740989 , 8.30805019,
       7.50746841, 7.85326724, 8.21442993, 7.08995726, 5.89970266,
       4.97106878, 3.55931552, 2.95368949, 1.70281776, 2.80171011,
       3.64553612, 4.39127633, 5.00797867, 4.01032337, 5.63804442,
       6.64272879, 6.71584517, 6.80248847, 7.36602973, 6.01185099,
       4.61637208, 5.19722985, 5.83036138, 6.40934177, 7.5072947 ,
       8.07818928, 8.6527837 , 8.6766878 , 8.92642445, 7.85159103,
       7.03456119, 5.76908703, 5.25576696, 6.88980347, 7.87981014,
       8.44956413, 9.33251186, 8.18524822, 7.17407468, 6.6214592 ,
       3.94309547, 3.10418515, 2.74740844, 5.17482395, 4.31482203,
       6.29746987, 5.10977451, 4.28898845, 5.23775134, 6.18285645,
       5.90297551, 6.9541538 , 6.68801114, 7.61111416, 6.81870204,
       7.63758179, 8.18746005, 8.02748901, 9.31758089, 8.55267427,
       8.68980223, 6.5348159 , 5.57424421, 4.83045235, 3.76177

In [15]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [18]:
z=1/(1+np.exp(-yp1))
z

array([0.99278586, 0.9533664 , 0.98932762, 0.99729533, 0.99866711,
       0.99773596, 0.99875073, 0.99926341, 0.99906507, 0.99975354,
       0.99945133, 0.99961167, 0.99972935, 0.99916726, 0.99726723,
       0.99311204, 0.97232917, 0.95043757, 0.84590239, 0.94276817,
       0.97455685, 0.9877666 , 0.99335998, 0.98219522, 0.9964528 ,
       0.99869823, 0.9987899 , 0.99889023, 0.99936803, 0.99755644,
       0.99020822, 0.99449857, 0.99707159, 0.9983566 , 0.99945124,
       0.99968986, 0.99982539, 0.99982951, 0.99986719, 0.99961102,
       0.99911987, 0.99688711, 0.99480974, 0.99898292, 0.99962184,
       0.99978605, 0.99991151, 0.99972134, 0.99923439, 0.99867028,
       0.98098064, 0.95706505, 0.93976682, 0.99437461, 0.98680744,
       0.99816243, 0.99399879, 0.98646686, 0.99471588, 0.99793973,
       0.99727613, 0.99904625, 0.99875579, 0.99950532, 0.99890805,
       0.99951824, 0.99972196, 0.99967374, 0.99991018, 0.99980701,
       0.99983174, 0.99855011, 0.99622   , 0.99208031, 0.97728

In [19]:
error=sum(y*np.log(z)+(1-y)*np.log(1-z))*(-1)
error

281.32972527968235