In [1]:
import pandas as pd
import random 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('logisticcodedata2.csv')

In [3]:
x1=dataset.iloc[:,0]
x2=dataset.iloc[:,1]
y=dataset.iloc[:,-1]

In [4]:
x1=np.matrix(x1)
x2=np.matrix(x2)
y=np.matrix(y)
print(x1.shape)
print(x2.shape)
print(y.shape)

(1, 100)
(1, 100)
(1, 100)


In [5]:
w0=random.random()
w1=random.random()
w2=random.random()
yp=w0+(w1*x1)+(w2*x2)
print(yp)
print(y)

[[ 4.84743953  2.85918097  4.22566871  5.57352497  6.50500833  6.02779213
   6.74032449  7.42258512  6.91950634  8.42825591  7.43857553  8.00457087
   8.74986007  7.52988287  6.17714659  5.03617781  3.50418473  2.69612888
   1.64408914  2.76388234  3.30373122  3.97879778  4.60506864  4.16326089
   5.79055259  6.81029578  6.9966073   5.92219289  6.728015    5.37773197
   4.09735584  5.05230756  5.75544396  6.56574412  7.78814808  8.47270148
   9.09667956  8.87757867  9.19893148  7.68528598  6.7935612   5.63430923
   5.13146588  6.9148564   8.00220314  8.96400064  9.98855425  8.53549463
   7.70922518  7.07124966  4.8321289   3.7796448   3.22067769  5.76538572
   4.79916313  7.01570961  5.87964211  5.0484873   6.2057463   7.24881851
   6.81565199  8.02401004  7.62585072  8.68286133  7.99387228  8.8553094
   9.45130851  9.04367827 10.40566597  9.61175746  9.96118011  8.14566407
   6.9231746   6.04306361  4.86026833  3.99631358  2.98351311  4.36951496
   5.37999617  4.20622744  5.97600585  

In [6]:
print(yp.shape)
print(y.shape)

(1, 100)
(1, 100)


In [7]:
z=1/(1+np.exp(-yp))
z

matrix([[0.99221267, 0.94579132, 0.98559498, 0.99621729, 0.99850631,
         0.99759499, 0.99881913, 0.99940275, 0.99901266, 0.99978145,
         0.99941222, 0.99966618, 0.99984154, 0.99946349, 0.99792796,
         0.99354342, 0.9708066 , 0.93679783, 0.83809058, 0.9406926 ,
         0.96455659, 0.98163545, 0.99009801, 0.98468156, 0.99695302,
         0.99889885, 0.99908586, 0.99732784, 0.99880452, 0.99540295,
         0.98365504, 0.99364607, 0.99684449, 0.9985942 , 0.99958555,
         0.99979094, 0.99988798, 0.99986054, 0.99989886, 0.99954067,
         0.99888029, 0.99643958, 0.9941268 , 0.99900806, 0.99966539,
         0.99987208, 0.99995408, 0.99980367, 0.99955153, 0.99915155,
         0.99209347, 0.97767881, 0.96160504, 0.99687561, 0.99183065,
         0.99910314, 0.99721201, 0.99362191, 0.99798626, 0.99928949,
         0.99890472, 0.9996726 , 0.99951256, 0.99983056, 0.99966259,
         0.9998574 , 0.99992142, 0.99988188, 0.99996974, 0.99993307,
         0.99995281, 0.99971009, 0

In [8]:
z.shape

(1, 100)

In [9]:
z=z.T

In [10]:
z.shape

(100, 1)

In [11]:
error=sum(y*np.log(z)+(1-y)*np.log(1-z))*(-1)

In [12]:
error

matrix([[342.6317325]])

In [13]:
dj0=-1*sum(y*(1-z)-(1-y)*z)
dj0

matrix([[49.21213644]])

In [19]:
x1.shape

(1, 100)

In [20]:
y.shape

(1, 100)

In [21]:
z.shape

(100, 1)

In [17]:
dj1=-1*sum((y*(1-z)*x1)-((1-y)*z*x1))
dj1

matrix([[222.399487  , 120.2892251 , 208.70374943, 285.90774907,
         317.03934659, 285.90774907, 314.54921248, 338.21040768,
         334.47520653, 401.71866976, 364.35681577, 375.56734045,
         381.79267571, 323.26468185, 263.49654214, 219.9093529 ,
         146.4405544 , 120.2892251 ,  44.33029251, 104.10335342,
         161.38628024, 204.96854827, 238.59027989, 163.87641434,
         253.53108451, 308.32387722, 308.32387722, 354.39627936,
         376.81240751, 302.09854196, 221.15441995, 239.83534694,
         272.2120115 , 295.86828549, 351.90614525, 379.30254161,
         409.18907207, 419.14960849, 430.35521195, 386.77294392,
         344.43574294, 270.96694445, 242.32548104, 326.999883  ,
         378.05747456, 395.48841329, 439.07560253, 386.77294392,
         324.5097489 , 297.11335254, 133.98988388,  95.38788406,
          82.93229233, 212.43895058, 168.85668255, 269.7218774 ,
         202.47841417, 157.64615787, 202.47841417, 251.04095041,
         241.08041399, 29

In [18]:
dj2=-1*sum((y*(1-z)*x2)-((1-y)*z*x2))
dj2

matrix([[130.34818579,  75.97369624,  93.4538471 , 121.60811036,
         165.3035663 , 159.47684935, 187.63603382, 218.70365555,
         180.83983778, 233.27044794, 191.51887138, 226.4742519 ,
         281.81329932, 243.94948155, 196.37118804, 148.79781574,
         101.21952223,  62.38130415,  57.5289875 ,  85.68325076,
          68.20802111,  76.94809654,  92.48436801, 137.14438183,
         175.01312082, 200.25894681, 215.79029708,  75.97369624,
         118.69967309,  87.62713014,  69.17750019, 128.40922761,
         151.71117422, 193.45782956, 234.23992703, 261.4247112 ,
         280.84382023, 251.71515668, 266.28194906, 187.63603382,
         159.47684935, 142.97109879, 132.29206518, 188.60551291,
         223.56089342, 284.7266578 , 322.59539679, 258.51135272,
         257.54187363, 234.23992703, 225.49985159, 179.86543747,
         146.85393635, 217.73417646, 184.72267534, 259.48575302,
         238.12276459, 217.73417646, 265.30754876, 299.29345019,
         274.04762419, 31